### ISSUE TITLE
Restart stuck (build 195)

### ISSUE THREAD

**Issue by BoostOver** [negan07/ancistrus#14]
When push on web GUI restart system or start the system for the first time ,router stuck with 1 and 2 LED ETH on for more and more minute.
Some time the restart go OK, but it is long (with 1 and 2 LED ETH ON)
I'm not only, in the forum (hwupgrade.it) there are others member .
And if the power fails and we are not at home?

Anyway, you did a great job.
Many thanks

**Comment by negan07** [comment]
In fact i've noticed this stuck but I didn't take too care of it because of many other modifications in act.

Kernel is the key without doubt.

To analize the problem deeply serial debug could help but it require opening the router and pinning the board with warranty issues.

Safer and quicker to find which of the patches inserted gives troubles.

**Comment by negan07** [comment]
both kernel & uclibc fpu neon created the problem maybe
now removed
reverted to soft float

the release zip file has been bumped in the morning
after modifications 24 hours of hot&cold reboots never stucked

master committed too

**Comment by BoostOver** [comment]
Thanks, master ;-)
