### ISSUE TITLE
QOS always active

### ISSUE THREAD

**Issue by BoostOver** [negan07/ancistrus#17]
Flag or not flag in GUI, QoS is always on.

**Comment by negan07** [comment]
yes

It happens also with the older package
this is due to rc command from netgear environment
it checks for setting after running the command and not before

infact if running:
`/usr/sbin/rc_app/rc_qos stop`

it stops

I've noticed this thing first on openvpn too
If trying to
```
nvram set openvpn_enable=0
rc openvpn restart
```
vpn not starting

while 
```
nvram set openvpn_enable=1
rc openvpn restart
```
starting

now looking good:

`opkg update`
`opkg upgrade`

**Comment by BoostOver** [comment]
Great.
