### ISSUE TITLE
Build #265 opkg upgrade removing xdslctl reference

### ISSUE THREAD

**Issue by BoostOver** [negan07/ancistrus#24]
Any attempt to update a package with OPKG corrupts the firmware.
Example, try updating the xdsl driver .....

**Comment by negan07** [comment]
yes...

ther is a problem with opkg syncing packages

for some reason it removes xdslctl making connection impossible at next reboot

blocking the release until investigations

**Comment by BoostOver** [comment]
And gui stuck/crash

**Comment by negan07** [comment]
package installed into monolithic cannot be sync with rep because coming from an offline installation: so the status file is different and it cause package upgrading the first time installing a package like xdsl driver

there was an error into core postinstall creating a symlink overwriting xdslctl.bin

now core package bumped and problem solved

the gui stuck noticed was certainly related to xdslctl missing

**Comment by BoostOver** [comment]
Thanks
