### ISSUE TITLE
IOS Genie App local login failure on monolithic firmware

### ISSUE THREAD

**Issue by lentis88** [negan07/ancistrus#51]
With the latest 526 firmware the Genie app does not work properly anymore, always reports "wrong password".
I tried to reset it several times and reinstall the official 1.0.1.70 version and the app works correctly.
Someone I encountered the same problem?

**Comment by negan07** [comment]
did this involved also #454 ?

**Comment by lentis88** [comment]
Nope, but apparently it's a problem of the app.
On the Netgear> Genie forum, many people have the same problem.

**Comment by negan07** [comment]
did some test

build #526 with latest package updates (included openssl)
genie app from windows: all good
genie app from ipk android: all good
genie app from ios: not good

in this case, got the login after some tries on the genie gui: tick/untick save password and/or setup router ip and/or pwd visibile/not visible and then after some tries it did it

I agree with genie app mobile problem occurred on the latest update

**Comment by negan07** [comment]
In this case the fix must arrive from netgear devs because the genie source code is not available

anyway it seems the bug ticket has been dispatched as confirmed in the discussion above

**Comment by negan07** [comment]
Maybe found the bug.

Not a specific genie app issue but a firmware regeneration one present on the source code.

Every time a monolithic or original firmware was made, the file `/www.eng/currentsetting.htm` was recreated but in an unappropriate way with wrong variables.

The original firmware wasn't affected by this problem because its  `/www.eng/currentsetting.htm` file was right and different from the one obtainable after making the firmware from sources.

This is the correct one
[currentsetting.zip](https://github.com/negan07/ancistrus/files/3018247/currentsetting.zip)

For those IOS people users wanting to fix the local login Genie app problem quickly, simply log the console and:

`echo "LoginMethod=2.0" >>/www.eng/currentsetting.htm`

should be satisfying
Package core update will come.

In the meanwhile it should be safer to compare each orig firmware file with those present on sources to see if there are other unwanted mismatches.
