### ISSUE TITLE
Blank chars query parsing from mini_httpd-1.30_170

### ISSUE THREAD

**Issue by f54rog** [negan07/ancistrus#86]
After the October updates, the info regarding the line has disappeared from the Ancistrus Home page.
Any suggestions?
Thanks in advanc
![Ancistrus home (2)](https://user-images.githubusercontent.com/50657473/137910461-58c8be94-12b6-4f20-9f28-0fcae7278d4b.png)
e

**Comment by negan07** [comment]
There's something missing maybe: partition usage @74% is too low. Rescue firmware never went under 80% usage.

Has something been removed manually ?

**Comment by negan07** [comment]
Found the bug, related to a wrong string chars interpreter on javascript, fixed on the next `core` upgrade.

The trick suggested is valid only until next device reboot only.

If possible, to investigate on 74% on rootfs usage only, can you please post the result of the cmd:

`df`

**Comment by negan07** [comment]
Reopen because further investigations have found out at least 2 more issues.

openssh `keys download button`

core `setup utilities download nvram button`

With the recap page stats above, all seem related to vendor's latest `mini_httpd` modifications, here added.

[D7000_V1.0.1.82_apps_mini_httpd-1.17beta1-000-all.zip](https://github.com/negan07/ancistrus/files/7464391/D7000_V1.0.1.82_apps_mini_httpd-1.17beta1-000-all.zip)

In particular:

```
@@ -1493,15 +1510,136 @@
  */
 int path_exist(char *path, char *paths[], char *method_str)
 {
-	int i;
-
-	for (i = 0; paths[i]; i++)
+	if ((strcasestr(path, "%2") !=NULL) || (strcasestr(path, "%3") != NULL))
+	{	
+		SC_CFPRINTF("path:%s\n", path);
+		strdecode(path, path);		
+		SC_CFPRINTF("path after decode: %s\n", path);
+	}
```
involving in fact, all the `location.href` method calls on the webpages, with blanks.

**Comment by negan07** [comment]
In the latest mini_httpd own snapshot, the vendor opted to decode query path on some special code chars (ebginning with 2 & 3 code num): this involves query GET methods avoiding blank char spaces ( `%20` ):f or this reason, from now, all the query get string like `href` must encode blank with `+`

openssh & core package updates fixes it.

**Comment by negan07** [comment]
The 1.0.1.84 latest mini_httpd patch update has removed also:

`if ((strcasestr(path, "%2") !=NULL) || (strcasestr(path, "%3") != NULL))`

condition, decoding all the paths in any case
